export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
